/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.um;


import com.cloud.nest.db.um.tables.User;


/**
 * Convenience access to all tables in um.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>um.user</code>.
     */
    public static final User USER = User.USER;
}
