/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.um;


import com.cloud.nest.db.DefaultCatalog;
import com.cloud.nest.db.um.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Um extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>um</code>
     */
    public static final Um UM = new Um();

    /**
     * The table <code>um.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Um() {
        super("um", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            User.USER
        );
    }
}
