/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.fm.tables.records;


import com.cloud.nest.db.fm.tables.ReportJob;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportJobRecord extends UpdatableRecordImpl<ReportJobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fm.report_job.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fm.report_job.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fm.report_job.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fm.report_job.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fm.report_job.last_reported_user_id</code>.
     */
    public void setLastReportedUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>fm.report_job.last_reported_user_id</code>.
     */
    public Long getLastReportedUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fm.report_job.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>fm.report_job.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>fm.report_job.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>fm.report_job.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fm.report_job.completed</code>.
     */
    public void setCompleted(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>fm.report_job.completed</code>.
     */
    public Boolean getCompleted() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportJobRecord
     */
    public ReportJobRecord() {
        super(ReportJob.REPORT_JOB);
    }

    /**
     * Create a detached, initialised ReportJobRecord
     */
    public ReportJobRecord(Long id, String type, Long lastReportedUserId, LocalDateTime created, LocalDateTime updated, Boolean completed) {
        super(ReportJob.REPORT_JOB);

        setId(id);
        setType(type);
        setLastReportedUserId(lastReportedUserId);
        setCreated(created);
        setUpdated(updated);
        setCompleted(completed);
        resetChangedOnNotNull();
    }
}
