version: '3.9'
services:
  consul:
    image: consul:1.15.4
    hostname: localhost
    ports:
      - '8500:8500'

  postgres:
    image: postgres:16.1-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /d/Files/volumes/postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:2024.10.13
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      -  /d/Files/volumes/minio-data:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniominio
      - MINIO_DEFAULT_BUCKETS=default