version: '3.9'
services:
  consul:
    image: consul:1.15.4
    hostname: localhost
    ports:
      - '8500:8500'

  postgres:
    image: postgres:16.1-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /d/Files/volumes/postgres-data:/var/lib/postgresql/data