server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        deregister: true
        healthCheckInterval: 10s
        health-check-url: http://host.docker.internal:${server.port}/actuator/health

    gateway:
      x-forwarded:
        for-append: false

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
