/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.auth;


import com.cloud.nest.db.auth.tables.Session;
import com.cloud.nest.db.auth.tables.SessionHistory;
import com.cloud.nest.db.auth.tables.User;
import com.cloud.nest.db.auth.tables.UserRole;
import com.cloud.nest.db.auth.tables.records.SessionHistoryRecord;
import com.cloud.nest.db.auth.tables.records.SessionRecord;
import com.cloud.nest.db.auth.tables.records.UserRecord;
import com.cloud.nest.db.auth.tables.records.UserRoleRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SessionRecord> SESSION_ID_PKEY = Internal.createUniqueKey(Session.SESSION, DSL.name("session_id_pkey"), new TableField[] { Session.SESSION.ID }, true);
    public static final UniqueKey<SessionHistoryRecord> SESSION_HISTORY_SESSION_ID_USER_ID_PKEY = Internal.createUniqueKey(SessionHistory.SESSION_HISTORY, DSL.name("session_history_session_id_user_id_pkey"), new TableField[] { SessionHistory.SESSION_HISTORY.SESSION_ID, SessionHistory.SESSION_HISTORY.USER_ID }, true);
    public static final UniqueKey<UserRecord> USER_ID_PKEY = Internal.createUniqueKey(User.USER, DSL.name("user_id_pkey"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserRecord> USER_USERNAME_KEY = Internal.createUniqueKey(User.USER, DSL.name("user_username_key"), new TableField[] { User.USER.USERNAME }, true);
    public static final UniqueKey<UserRoleRecord> USER_ROLE_USER_ID_ROLE_PKEY_CONSTRAINT = Internal.createUniqueKey(UserRole.USER_ROLE, DSL.name("user_role_user_id_role_pkey_constraint"), new TableField[] { UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE }, true);
}
