/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.auth;


import com.cloud.nest.db.auth.tables.Session;
import com.cloud.nest.db.auth.tables.User;
import com.cloud.nest.db.auth.tables.UserRole;


/**
 * Convenience access to all tables in auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>auth.session</code>.
     */
    public static final Session SESSION = Session.SESSION;

    /**
     * The table <code>auth.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>auth.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
