/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.pg_catalog;


import com.cloud.nest.db.DefaultCatalog;

import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgCatalog extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pg_catalog</code>
     */
    public static final PgCatalog PG_CATALOG = new PgCatalog();

    /**
     * No further instances allowed
     */
    private PgCatalog() {
        super("pg_catalog", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
