/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.pg_catalog;


import com.cloud.nest.db.pg_catalog.routines.FmgrCValidator;
import com.cloud.nest.db.pg_catalog.routines.FmgrInternalValidator;
import com.cloud.nest.db.pg_catalog.routines.FmgrSqlValidator;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in pg_catalog.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>pg_catalog.fmgr_c_validator</code>
     */
    public static void fmgrCValidator(
          Configuration configuration
        , Long __1
    ) {
        FmgrCValidator p = new FmgrCValidator();
        p.set__1(__1);

        p.execute(configuration);
    }

    /**
     * Call <code>pg_catalog.fmgr_internal_validator</code>
     */
    public static void fmgrInternalValidator(
          Configuration configuration
        , Long __1
    ) {
        FmgrInternalValidator p = new FmgrInternalValidator();
        p.set__1(__1);

        p.execute(configuration);
    }

    /**
     * Call <code>pg_catalog.fmgr_sql_validator</code>
     */
    public static void fmgrSqlValidator(
          Configuration configuration
        , Long __1
    ) {
        FmgrSqlValidator p = new FmgrSqlValidator();
        p.set__1(__1);

        p.execute(configuration);
    }
}
