/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.auth.tables.records;


import com.cloud.nest.db.auth.tables.Session;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionRecord extends UpdatableRecordImpl<SessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.session.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.session.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>auth.session.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.session.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>auth.session.client_ip</code>.
     */
    public void setClientIp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.session.client_ip</code>.
     */
    public String getClientIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.session.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.session.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.session.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.session.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>auth.session.json_properties</code>.
     */
    public void setJsonProperties(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.session.json_properties</code>.
     */
    public String getJsonProperties() {
        return (String) get(5);
    }

    /**
     * Setter for <code>auth.session.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.session.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>auth.session.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.session.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>auth.session.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.session.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>auth.session.last_active</code>.
     */
    public void setLastActive(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.session.last_active</code>.
     */
    public LocalDateTime getLastActive() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionRecord
     */
    public SessionRecord() {
        super(Session.SESSION);
    }

    /**
     * Create a detached, initialised SessionRecord
     */
    public SessionRecord(String id, String username, String clientIp, String userAgent, String status, String jsonProperties, LocalDateTime created, LocalDateTime updated, LocalDateTime expiresAt, LocalDateTime lastActive) {
        super(Session.SESSION);

        setId(id);
        setUsername(username);
        setClientIp(clientIp);
        setUserAgent(userAgent);
        setStatus(status);
        setJsonProperties(jsonProperties);
        setCreated(created);
        setUpdated(updated);
        setExpiresAt(expiresAt);
        setLastActive(lastActive);
        resetChangedOnNotNull();
    }
}
