/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.fm;


import com.cloud.nest.db.DefaultCatalog;
import com.cloud.nest.db.fm.tables.File;
import com.cloud.nest.db.fm.tables.Report;
import com.cloud.nest.db.fm.tables.ReportJob;
import com.cloud.nest.db.fm.tables.SharedFile;
import com.cloud.nest.db.fm.tables.UserStorage;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fm extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fm</code>
     */
    public static final Fm FM = new Fm();

    /**
     * The table <code>fm.file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>fm.report</code>.
     */
    public final Report REPORT = Report.REPORT;

    /**
     * The table <code>fm.report_job</code>.
     */
    public final ReportJob REPORT_JOB = ReportJob.REPORT_JOB;

    /**
     * The table <code>fm.shared_file</code>.
     */
    public final SharedFile SHARED_FILE = SharedFile.SHARED_FILE;

    /**
     * The table <code>fm.user_storage</code>.
     */
    public final UserStorage USER_STORAGE = UserStorage.USER_STORAGE;

    /**
     * No further instances allowed
     */
    private Fm() {
        super("fm", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            File.FILE,
            Report.REPORT,
            ReportJob.REPORT_JOB,
            SharedFile.SHARED_FILE,
            UserStorage.USER_STORAGE
        );
    }
}
