/*
 * This file is generated by jOOQ.
 */
package com.cloud.nest.db.fm;


import com.cloud.nest.db.fm.tables.File;
import com.cloud.nest.db.fm.tables.SharedFile;
import com.cloud.nest.db.fm.tables.UserStorage;


/**
 * Convenience access to all tables in fm.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>fm.file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>fm.shared_file</code>.
     */
    public static final SharedFile SHARED_FILE = SharedFile.SHARED_FILE;

    /**
     * The table <code>fm.user_storage</code>.
     */
    public static final UserStorage USER_STORAGE = UserStorage.USER_STORAGE;
}
